<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Defines\**" />
    <EmbeddedResource Remove="Defines\**" />
    <None Remove="Defines\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="H.Pipes" Version="15.0.0" />
    <PackageReference Include="ZTool_Re" Version="1.1.2" />
  </ItemGroup>

</Project>
